insert  into  member(ID, Name, Surname, Gender, Age, Salary, Tel, Email) values
('0001','Nhamjit','Rakmarnrean','Male','25','22000','0812345234','nhamjit@rmutsb.ac.th');

insert  into  member(ID, Name, Surname, Gender, Age, Salary, Tel, Email) values
('0002','PRUCH','TAREESAK','Male','19','23000','0671239852','PRUCH@rmutsb.ac.th');

insert  into  member(ID, Name, Surname, Gender, Age, Salary, Tel, Email) values
('0003','THANYAKORN','SAENGCHAN','FeMale','20','23000','0985214563','thanyakorn@rmutsb.ac.th');

insert  into  member(ID, Name, Surname, Gender, Age, Salary, Tel, Email) values
('0004','NARONGWIT','MOSIKARAT','Male','20','28000','0892541210','ARM01@rmutsb.ac.th');

insert  into  member(ID, Name, Surname, Gender, Age, Salary, Tel, Email) values
('0005','JKLO','KOOKK','FeMale','19','26000','0812356489','ABCDEF@rmutsb.ac.th');
